module Everything where

import Cat.NaturalTransformation
import Cat.TerminalObject
import Cat.Limit
import Cat.Cones.FromNaturalTransformation
import Cat.Cones.FromQuiver
import Cat.NaturalTransformations.Identity
import Cat.NaturalTransformations.Compose
import Cat.NaturalTransformations.FromQuiver
import Cat.Setoid
import Cat.Setoids.Function
import Cat.Setoids.Unit
import Cat.Setoids.Empty
import Cat.Setoids.SetSetoid
import Cat.Cone
import Cat.NaturalIsomorphisms.FromNaturalTransformations
import Cat.NaturalIsomorphisms.Yoneda
import Cat.Categories.Setoid
import Cat.Categories.Cone
import Cat.Categories.Monoid
import Cat.Categories.Category
import Cat.Categories.Minimal
import Cat.Categories.Product
import Cat.Categories.SetCat
import Cat.Categories.Free
import Cat.Categories.Functor
import Cat.Limits.Pullback
import Cat.Limits.Product
import Cat.Representations.FromUniversalElement
import Cat.Adjunction
import Cat.InitialObjects.SetCat.Bot
import Cat.Category
import Cat.Quivers.Pullback
import Cat.Quivers.Product
import Cat.Representable
import Cat.TerminalObjects.Cone.Limit
import Cat.TerminalObjects.SetCat.Unit
import Cat.UniversalElement
import Cat.Pullbacks.SetCat.PairEq
import Cat.Product
import Cat.Endofunctors.Identity
import Cat.Endofunctors.Setoid.Vec
import Cat.Endofunctors.SetCat.List
import Cat.Isomorphism
import Cat.InitialObject
import Cat.NaturalIsomorphism
import Cat.Functor
import Cat.Functors.SetToSetoid
import Cat.Functors.Compose
import Cat.Functors.FromQuiver
import Cat.Functors.FunctorApply
import Cat.Functors.Constant
import Cat.Functors.Hom
import Cat.Functors.Yoneda